#include "ui.h"

#ifdef ESP_PLATFORM

#include "board.h"
#include "bb_display.h"
#include "bb_nv.h"
#include "bb_log.h"
#include "bb_system.h"

#include <string.h>
#include <stdio.h>
#include <inttypes.h>

// RGB565 colors
#define COLOR_BLACK      0x0000
#define COLOR_WHITE      0xFFFF
#define COLOR_AMBER      0xC3A0
#define COLOR_CYAN       0x07FF
#define COLOR_YELLOW     0xFFE0

// Logo: 56x56 1bpp bitmap, foreground color 0xFBE0
#define LOGO_W 56
#define LOGO_H 56
#define LOGO_BITS_LEN ((LOGO_W * LOGO_H + 7) / 8)
#define LOGO_FG_COLOR 0xFBE0

// Auto-generated by scripts/svg_to_logo.py — do not edit
static const uint8_t s_logo_bits[LOGO_BITS_LEN] = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03, 0xC0,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x1F, 0xF8, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x3F, 0xE4, 0x00, 0x00, 0x00, 0x00, 0x00, 0x7F, 0xFE, 0x00, 0x00, 0x00,
    0x00, 0x00, 0xFF, 0xFE, 0x00, 0x00, 0x00, 0x00, 0x01, 0xE7, 0xFC, 0x00,
    0x00, 0x00, 0x00, 0x01, 0xEE, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0xCC,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x03, 0xCC, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x01, 0xEC, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0xE4, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x01, 0xF0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFC, 0x00,
    0x00, 0x00, 0x00, 0x00, 0xFE, 0xFF, 0x9E, 0x00, 0x00, 0x00, 0x07, 0xFF,
    0x7F, 0xE7, 0xC0, 0x00, 0x00, 0x1F, 0xFF, 0x9F, 0xF9, 0xE0, 0x00, 0x00,
    0x3F, 0xFF, 0x8F, 0xFC, 0x70, 0x00, 0x00, 0x3F, 0x3F, 0xF3, 0xFE, 0x78,
    0x00, 0x00, 0x3F, 0x7F, 0xFE, 0x7E, 0x78, 0x00, 0x00, 0x3F, 0xC0, 0x7F,
    0xFC, 0x78, 0x00, 0x00, 0x3F, 0xF8, 0x07, 0xF8, 0xFC, 0x00, 0x00, 0x1F,
    0xFF, 0x80, 0x07, 0xFC, 0x00, 0x00, 0x0F, 0xFF, 0xFF, 0xFF, 0xF8, 0x00,
    0x00, 0x03, 0xFF, 0xFF, 0xFF, 0xF8, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFE,
    0xF0, 0x00, 0x00, 0x00, 0x0F, 0xFF, 0xFF, 0xC0, 0x00, 0x00, 0x00, 0x00,
    0x7F, 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

static void fmt_hashrate(double hr, char *buf, size_t len)
{
    const char *unit;
    if (hr >= 1e12) { hr /= 1e12; unit = "TH/s"; }
    else if (hr >= 1e9) { hr /= 1e9; unit = "GH/s"; }
    else if (hr >= 1e6) { hr /= 1e6; unit = "MH/s"; }
    else if (hr >= 1e3) { hr /= 1e3; unit = "kH/s"; }
    else { unit = "H/s"; }
    snprintf(buf, len, "%.1f %s", hr, unit);
}

static void fmt_uptime(int64_t us, char *buf, size_t len)
{
    int secs = (int)(us / 1000000);
    int days = secs / 86400;
    int hours = (secs % 86400) / 3600;
    int mins = (secs % 3600) / 60;

    if (days > 0) snprintf(buf, len, "%dd %dh", days, hours);
    else if (hours > 0) snprintf(buf, len, "%dh %dm", hours, mins);
    else snprintf(buf, len, "%dm %ds", mins, secs % 60);
}

void ui_show_splash(void)
{
    if (!bb_display_ready()) return;

    uint16_t w = bb_display_width();
    uint16_t h = bb_display_height();

    bb_display_clear(COLOR_BLACK);

    if (w >= (uint16_t)(LOGO_W + 8)) {
        // Wide display (ST7735 160x80): logo left, text right
        int16_t logo_x = 2;
        int16_t logo_y = (int16_t)((h - LOGO_H) / 2);

        // Blit logo row by row
        uint16_t row_buf[LOGO_W];
        for (int row = 0; row < LOGO_H; row++) {
            for (int col = 0; col < LOGO_W; col++) {
                int idx = row * LOGO_W + col;
                bool on = (s_logo_bits[idx / 8] >> (7 - (idx % 8))) & 1;
                row_buf[col] = on ? LOGO_FG_COLOR : COLOR_BLACK;
            }
            bb_display_blit(logo_x, (int16_t)(logo_y + row), LOGO_W, 1, row_buf);
        }

        int16_t text_x = (int16_t)(logo_x + LOGO_W + 4);
        int16_t text_y = (int16_t)((h - 16) / 2);
        bb_display_draw_text(text_x, text_y, "TaipanMiner", NULL,
                             COLOR_AMBER, COLOR_BLACK);
    } else {
        // Narrow display (SSD1306 128x32): centered text
        bb_display_draw_text(20, 8, "TaipanMiner", NULL, COLOR_WHITE, COLOR_BLACK);
    }
    bb_display_flush();
}

void ui_show_prov(const char *ssid, const char *password)
{
    if (!bb_display_ready()) return;

    uint16_t h = bb_display_height();

    bb_display_clear(COLOR_BLACK);

    if (h >= 64) {
        bb_display_draw_text(0,  4, "WiFi Setup", NULL, COLOR_YELLOW, COLOR_BLACK);
        bb_display_draw_text(0, 24, "SSID:",       NULL, COLOR_CYAN,   COLOR_BLACK);
        bb_display_draw_text(0, 40, ssid,           NULL, COLOR_WHITE,  COLOR_BLACK);
        bb_display_draw_text(0, 56, "Pass:",        NULL, COLOR_CYAN,   COLOR_BLACK);
        bb_display_draw_text(40, 56, password,      NULL, COLOR_WHITE,  COLOR_BLACK);
    } else {
        char ssid_buf[17];
        strncpy(ssid_buf, ssid, 16);
        ssid_buf[16] = '\0';
        bb_display_draw_text(0,  0, ssid_buf, NULL, COLOR_WHITE, COLOR_BLACK);

        char pw_buf[14];
        snprintf(pw_buf, sizeof(pw_buf), "PW: %s", password);
        bb_display_draw_text(0, 16, pw_buf, NULL, COLOR_WHITE, COLOR_BLACK);
    }
    bb_display_flush();
}

void ui_display_off(void)
{
    bb_display_off();
}

// ---- show_status per-board implementations ----

#ifdef BOARD_DISPLAY_PANEL_ST77XX

// Per-row text rasterizer using bb_display_font_8x16.
// Renders one pixel row (font_row) of text at x-offset into line[].
// line is LCD_WIDTH wide; out-of-bounds columns are skipped.
static void render_text_row_into_line(uint16_t *line, int x, const char *text,
                                      int font_row, uint16_t fg, uint16_t bg,
                                      int line_w)
{
    const bb_display_font_t *font = &bb_display_font_8x16;
    for (int ci = 0; text[ci] != '\0'; ci++) {
        uint8_t ch = (uint8_t)text[ci];
        if (ch < font->first_codepoint ||
            (ch - font->first_codepoint) >= font->glyph_count) ch = font->first_codepoint;
        const uint8_t *glyph_rows = &font->bitmap[(ch - font->first_codepoint) * font->glyph_h];
        uint8_t bits = glyph_rows[font_row];
        int cx = x + ci * font->glyph_w;
        for (int col = 0; col < font->glyph_w; col++) {
            int px = cx + col;
            if (px >= 0 && px < line_w) {
                line[px] = (bits & (0x80 >> col)) ? fg : bg;
            }
        }
    }
}

// Per-row logo rasterizer: writes LOGO_W pixels into line[] at logo_x.
static void render_logo_row_into_line(uint16_t *line, int logo_x, int logo_row)
{
    for (int col = 0; col < LOGO_W; col++) {
        int idx = logo_row * LOGO_W + col;
        bool on = (s_logo_bits[idx / 8] >> (7 - (idx % 8))) & 1;
        line[logo_x + col] = on ? LOGO_FG_COLOR : COLOR_BLACK;
    }
}

// Virtual strip: page0=splash(h px), page1=stats(h px), page2=network(h px).
// State 0: hold splash 5s (100 ticks @ 50ms). State 1: scroll 1px/3 ticks.
static void show_status_st7735(const display_status_t *status)
{
    static int s_state;
    static int s_tick;
    static int s_offset;

    uint16_t w = bb_display_width();
    uint16_t h = bb_display_height();
    int total = (int)h * 3;

    char stat_text[4][21];
    fmt_hashrate(status->hashrate, stat_text[0], 21);
    snprintf(stat_text[1], 21, "Shares: %" PRIu32 "/%" PRIu32,
             status->shares, status->rejected);
    snprintf(stat_text[2], 21, "Temp: %.1fC", status->temp_c);
    {
        char up[16];
        fmt_uptime(status->uptime_us, up, sizeof(up));
        snprintf(stat_text[3], 21, "Up: %s", up);
    }

    char net_text[5][21];
    const char *net_state;
    if (status->stratum_ok && status->mdns_ok)                    net_state = "NET ok";
    else if (status->wifi_retry_count > 0 || !status->stratum_ok) net_state = "NET rcon";
    else                                                           net_state = "NET off";
    snprintf(net_text[0], 21, "%s", net_state);
    const char *ssid = bb_nv_config_wifi_ssid();
    snprintf(net_text[1], 21, "%-13.13s%4ddBm", ssid ? ssid : "?", status->rssi);
    snprintf(net_text[2], 21, "%s", status->ip);
    uint32_t disc_mins = status->wifi_disc_age_s / 60;
    snprintf(net_text[3], 21, "D:%-3u %-4um r:%d",
             status->wifi_disc_reason, (unsigned)disc_mins, status->wifi_retry_count);
    snprintf(net_text[4], 21, "MDNS:%s S:%s",
             status->mdns_ok ? "ok" : "--",
             status->stratum_ok ? "ok" : "r");

    int render_offset = (s_state == 0) ? 0 : s_offset;

    // Skip re-render every tick during hold-splash state (only first tick)
    if (s_state == 0 && s_tick > 0) {
        s_tick++;
        if (s_tick >= 100) { s_state = 1; s_tick = 0; s_offset = 0; }
        return;
    }

    // Skip scroll ticks that don't advance the pixel offset
    if (s_state == 1 && s_offset % 3 != 0) {
        s_offset++;
        if (s_offset >= total) { s_state = 0; s_tick = 0; }
        return;
    }

    // Splash logo geometry (page 0)
    int logo_x = 2;
    int logo_y_base = ((int)h - LOGO_H) / 2;
    int text_y_base = ((int)h - 16) / 2;
    int text_x = logo_x + LOGO_W + 4;

    // Stack-allocated scan line (LCD_WIDTH = 160 max)
    uint16_t line[160];

    for (int sy = 0; sy < (int)h; sy++) {
        int content_y = (sy + render_offset) % total;

        int page, page_y;
        if (content_y < (int)h) {
            page = 0; page_y = content_y;
        } else if (content_y < (int)h * 2) {
            page = 1; page_y = content_y - (int)h;
        } else {
            page = 2; page_y = content_y - (int)h * 2;
        }

        // Clear line to black
        for (int x = 0; x < (int)w; x++) line[x] = COLOR_BLACK;

        if (page == 0) {
            if (page_y >= logo_y_base && page_y < logo_y_base + LOGO_H) {
                render_logo_row_into_line(line, logo_x, page_y - logo_y_base);
            }
            if (page_y >= text_y_base && page_y < text_y_base + 16) {
                render_text_row_into_line(line, text_x, "TaipanMiner",
                                          page_y - text_y_base,
                                          COLOR_AMBER, COLOR_BLACK, (int)w);
            }
        } else if (page == 1) {
            int text_idx = page_y / 16;
            int font_row = page_y % 16;
            if (text_idx < 4) {
                uint16_t fg = (text_idx == 0) ? COLOR_AMBER : COLOR_WHITE;
                render_text_row_into_line(line, 0, stat_text[text_idx],
                                          font_row, fg, COLOR_BLACK, (int)w);
            }
        } else {
            int text_idx = page_y / 16;
            int font_row = page_y % 16;
            if (text_idx < 5) {
                uint16_t fg = (text_idx == 0) ? COLOR_AMBER : COLOR_WHITE;
                render_text_row_into_line(line, 0, net_text[text_idx],
                                          font_row, fg, COLOR_BLACK, (int)w);
            }
        }

        bb_display_blit(0, (int16_t)sy, w, 1, line);
    }

    bb_display_flush();

    // Advance state machine
    switch (s_state) {
    case 0:
        s_tick++;
        if (s_tick >= 100) { s_state = 1; s_tick = 0; s_offset = 0; }
        break;
    case 1:
        s_offset++;
        if (s_offset >= total) { s_state = 0; s_tick = 0; }
        break;
    }
}

#elif defined(BOARD_DISPLAY_PANEL_SSD1306)

static void show_status_ssd1306(const display_status_t *status)
{
    static int s_page;
    static int s_tick;

    if (++s_tick < 100) return;
    s_tick = 0;

    bb_display_clear(COLOR_BLACK);

    char buf[17];

    if (s_page == 0) {
        fmt_hashrate(status->hashrate, buf, sizeof(buf));
        bb_display_draw_text(0, 0, buf, NULL, COLOR_WHITE, COLOR_BLACK);

        snprintf(buf, sizeof(buf), "Shares:%" PRIu32 "/%" PRIu32,
                 status->shares, status->rejected);
        bb_display_draw_text(0, 16, buf, NULL, COLOR_WHITE, COLOR_BLACK);
    } else {
        snprintf(buf, sizeof(buf), "Temp: %.1fC", status->temp_c);
        bb_display_draw_text(0, 0, buf, NULL, COLOR_WHITE, COLOR_BLACK);

        char up[12];
        fmt_uptime(status->uptime_us, up, sizeof(up));
        snprintf(buf, sizeof(buf), "Up: %s", up);
        bb_display_draw_text(0, 16, buf, NULL, COLOR_WHITE, COLOR_BLACK);
    }

    s_page ^= 1;
    bb_display_flush();
}

#endif

void ui_show_status(const display_status_t *status)
{
    static bool s_was_off = false;

    if (!bb_display_ready() && !s_was_off) return;

    if (!bb_nv_config_display_enabled()) {
        if (!s_was_off) {
            bb_display_off();
            s_was_off = true;
        }
        return;
    }
    if (s_was_off) {
        bb_display_init();
        s_was_off = false;
    }

    if (!bb_display_ready()) return;

#if defined(BOARD_DISPLAY_PANEL_ST77XX)
    show_status_st7735(status);
#elif defined(BOARD_DISPLAY_PANEL_SSD1306)
    show_status_ssd1306(status);
#else
    (void)status;
#endif
}

#endif
