// Host test harness entry point. test_<module>_<behavior> functions live in
// sibling files; declared + RUN_TEST()'d manually below (no auto-discovery).
//
// tm_mining (TA-561v2 port): mining engine host tests -- SHA-256, share
// validation, work/header serialization, hashrate averaging, per-pool
// stats, the mine_nonce_range hot loop, and the tm_mining_producer
// (mining_gather/mining_desc) surface.
//
// tm_stratum (TA-560 port): protocol FSM (bb_fsm), the bb_serialize_json
// tok-recorder-driven JSON-RPC parse/build, backoff/watchdogs/reqid
// tracking, build_work() composition (test_work_build.c), and the
// TA-233/TA-494 stratum-never-blocks isolation invariant.
#include <unity.h>

// test_sha256.c
void test_sha256_empty_string(void);
void test_sha256_abc(void);
void test_sha256_two_blocks(void);
void test_sha256d_known(void);
void test_sha256_midstate(void);
void test_sha256_genesis_header(void);
void test_sha256_transform_words(void);
void test_sha256_transform_performance(void);
void test_sha256_build_abc_block(void);

// test_sha_self_test_gate.c
void test_sha256_sw_self_test_passes(void);
void test_mining_self_test_flag_default_false(void);
void test_mining_set_self_test_failed_flips_flag(void);
void test_sha256_check_abc_vector_accepts_correct_digest(void);
void test_sha256_check_abc_vector_rejects_wrong_digest(void);
void test_sha256_check_abc_vector_rejects_one_byte_flip(void);

// test_sha_overlap_hwrite_state.c
void test_mining_get_sha_overlap_state_default_unknown(void);
void test_mining_set_sha_overlap_safe_true_sets_safe(void);
void test_mining_set_sha_overlap_safe_false_sets_unsafe(void);
void test_mining_get_sha_hwrite_state_default_unknown(void);
void test_mining_set_sha_hwrite_safe_true_sets_safe(void);
void test_mining_set_sha_hwrite_safe_false_sets_unsafe(void);

// test_share_validate.c
void test_share_meets_network_target_genesis_block(void);
void test_share_meets_network_target_pool_share_fails(void);
void test_share_meets_network_target_exact_equals_target(void);
void test_share_meets_network_target_known_hit(void);
void test_share_meets_network_target_share_misses_network(void);
void test_share_meets_network_target_pool_diff_not_network(void);
void test_share_validate_invalid_target_rejects(void);
void test_share_validate_below_target_misses(void);
void test_share_validate_low_difficulty_just_under_floor_rejects(void);
void test_share_validate_low_difficulty_at_floor_accepts(void);
void test_share_validate_clean_valid_accept(void);

// test_work.c
void test_mining_hash_from_state_abc_vector(void);
void test_mining_hash_from_state_zero(void);
void test_set_header_nonce(void);
void test_nbits_to_target_genesis(void);
void test_nbits_to_target_high_diff(void);
void test_meets_target_pass(void);
void test_meets_target_fail(void);
void test_meets_target_equal(void);
void test_mining_round_trip_block1(void);
void test_mining_early_reject_byte_order(void);
void test_difficulty_target_meets_target_integration(void);
void test_version_rolling_mask_increment(void);
void test_is_target_valid_all_zero(void);
void test_is_target_valid_all_ff(void);
void test_is_target_valid_nonzero_msb31(void);
void test_is_target_valid_nonzero_msb30(void);
void test_is_target_valid_diff1(void);
void test_is_target_valid_diff512(void);
void test_is_target_valid_diff_001(void);
void test_package_result_round_trip_no_rolling(void);
void test_package_result_round_trip_with_rolling(void);

// test_work_build.c
void test_serialize_header_genesis(void);
void test_build_coinbase_hash(void);
void test_build_merkle_root_no_branches(void);
void test_build_merkle_root_with_branches(void);
void test_decode_stratum_prevhash(void);
void test_decode_stratum_prevhash_truncated(void);
void test_block1_full_pipeline(void);
void test_block170_merkle_and_hash(void);
void test_decode_stratum_prevhash_real(void);
void test_stratum_pipeline_block1(void);
void test_difficulty_to_target_diff1(void);
void test_difficulty_to_target_easy(void);
void test_difficulty_to_target_hard(void);
void test_difficulty_to_target_nan(void);
void test_difficulty_to_target_inf(void);
void test_difficulty_to_target_neg_inf(void);
void test_difficulty_to_target_negative(void);
void test_difficulty_to_target_zero(void);
void test_difficulty_to_target_tiny(void);
void test_difficulty_to_target_normal(void);
void test_build_work_block1_pipeline(void);
void test_build_work_extranonce2_hex_and_coinbase(void);
void test_build_work_rejects_null_job(void);
void test_build_work_rejects_null_out(void);
void test_build_work_rejects_null_extranonce1_with_nonzero_len(void);
void test_build_work_rejects_oversized_extranonce2(void);

// test_mining_avg.c
void test_avg_nan_safe_empty_all_nan(void);
void test_avg_nan_safe_single_value(void);
void test_avg_nan_safe_partial_nan(void);
void test_avg_nan_safe_all_populated(void);
void test_update_warmup_1m(void);
void test_update_full_1m_window(void);
void test_update_step_change(void);
void test_update_ring_wraparound(void);
void test_update_10m_blend_formula(void);
void test_update_1h_accumulation(void);
void test_update_with_zero_samples(void);
void test_update_mixed_values(void);
void test_mining_pool_eff_tick_zero_delta(void);
void test_mining_pool_eff_tick_typical(void);
void test_mining_pool_eff_tick_sum_decrease_clamps_to_zero(void);

// test_mining.c
void test_sw_backend_finds_block1_share(void);
void test_sw_backend_early_reject_low_diff(void);
void test_sw_backend_early_reject_high_diff(void);
void test_mine_nonce_range_counts(void);
void test_mine_nonce_range_stops_on_hit(void);
void test_mine_nonce_range_no_hit(void);
void test_mine_result_has_version_hex(void);
void test_pack_target_word0_diff1(void);
void test_pack_target_word0_easy_diff(void);
void test_pack_target_word0_hard_diff(void);
void test_build_block2_padding(void);
void test_package_result_no_version_rolling(void);
void test_package_result_version_rolling_submits_ver_bits(void);
void test_version_roll_stays_within_issue606_mask(void);
void test_header_rebuild_preserves_fixed_bit_issue606(void);
void test_mining_compute_pool_effective_hps_empty(void);
void test_mining_compute_pool_effective_hps_uptime_too_short(void);
void test_mining_compute_pool_effective_hps_typical(void);
void test_mining_compute_pool_effective_hps_diff1_share(void);
void test_mining_compute_pool_effective_hps_divide_by_zero_guard(void);
void test_mining_get_pool_effective_hashrate_host_stub(void);
void test_mining_get_pool_effective_rolling_host_stubs(void);
void test_pack_target_word0_exact_byte_order(void);
void test_share_reverify_block1_nonce(void);
void test_share_reverify_version_rolling(void);
void test_mining_efficiency_jth_known_case(void);
void test_mining_efficiency_jth_zero_hashrate(void);
void test_mining_efficiency_jth_negative_hashrate(void);
void test_mining_efficiency_jth_zero_power(void);
void test_mining_efficiency_jth_negative_power(void);
void test_mining_efficiency_jth_inverse_hashrate_scaling(void);
void test_sw_hash_nonce_rejects_over_target(void);
void test_block_found_cb_fires(void);
void test_block_found_cb_null_safe(void);
void test_mining_work_peek_default_false(void);
void test_mining_result_post_default_false(void);
void test_mining_queue_ops_bound_dispatches(void);
void test_mining_pause_gate_default_false(void);
void test_mining_pause_gate_bound(void);

// test_mining_pool_stats.c
void test_pool_stats_find_returns_existing_slot(void);
void test_pool_stats_case_insensitive_host_match(void);
void test_pool_stats_different_port_is_new_slot(void);
void test_pool_stats_alloc_into_empty_slot(void);
void test_pool_stats_lru_eviction_picks_lowest_last_seen(void);
void test_pool_stats_lru_eviction_skips_recent_slot(void);
void test_pool_stats_record_share_updates_matching_slot(void);
void test_pool_stats_record_block_increments_matching_slot(void);
void test_pool_stats_lifetime_blocks_survive_eviction(void);
void test_pool_stats_record_hashes_accumulates(void);
void test_pool_stats_null_slot_is_safe(void);
void test_pool_stats_slot_out_of_range_returns_null(void);
void test_pool_stats_find_or_alloc_null_host(void);
void test_pool_stats_init_runs_clean(void);
void test_pool_stats_reset_zeroes_all_state(void);

// test_mining_hotloop_sync.c
void test_mining_hotloop_finds_known_share(void);
void test_mining_hotloop_rejects_non_matching_nonce(void);

// test_tm_mining_producer.c
void test_mining_gather_unseeded_is_zeroed(void);
void test_mining_gather_round_trips_seeded_snapshot(void);
void test_mining_gather_round_trips_sha_self_test_failed_true(void);
void test_mining_gather_null_out_is_safe(void);
void test_mining_desc_snap_size_matches_struct(void);
void test_mining_desc_find_known_key(void);
void test_mining_desc_find_unknown_key(void);
void test_mining_desc_walk_matches_seeded_snapshot(void);

// test_stratum_backoff.c
void test_stratum_backoff_init(void);
void test_stratum_backoff_first_fail_sleeps_initial_then_doubles(void);
void test_stratum_backoff_progression_doubles_to_cap(void);
void test_stratum_backoff_caps_at_30s(void);
void test_stratum_backoff_reset_on_success(void);
void test_stratum_backoff_reset_restarts_doubling(void);

// test_stratum_reqid.c
void test_stratum_reqid_register_then_take(void);
void test_stratum_reqid_take_consumes(void);
void test_stratum_reqid_unregistered_id_returns_none(void);
void test_stratum_reqid_keepalive_survives_a_newer_overwrite(void);
void test_stratum_reqid_table_full_evicts_oldest(void);
void test_stratum_reqid_reset_clears_table(void);

// test_stratum_machine.c
void test_stratum_machine_build_configure(void);
void test_stratum_machine_build_configure_truncation(void);
void test_stratum_machine_build_subscribe(void);
void test_stratum_machine_build_subscribe_truncation(void);
void test_stratum_machine_build_authorize(void);
void test_stratum_machine_build_authorize_different_values(void);
void test_stratum_machine_build_authorize_truncation(void);
void test_stratum_machine_build_keepalive(void);
void test_stratum_machine_build_keepalive_small_difficulty(void);
void test_stratum_machine_build_keepalive_large_difficulty(void);
void test_stratum_machine_build_keepalive_truncation(void);
void test_handle_configure_result_golden(void);
void test_handle_configure_result_missing_field(void);
void test_handle_configure_result_pool_not_supported(void);
void test_handle_configure_result_narrow_mask_issue606(void);
void test_handle_subscribe_result_golden(void);
void test_handle_subscribe_result_too_long_extranonce1(void);
void test_handle_subscribe_result_invalid_no_extranonce(void);
void test_handle_subscribe_result_extranonce2_size_at_max_accepted(void);
void test_handle_subscribe_result_extranonce2_size_over_max_rejected(void);
void test_handle_subscribe_result_extranonce2_size_negative_rejected(void);
void test_handle_set_difficulty_1(void);
void test_handle_set_difficulty_65536(void);
void test_handle_set_difficulty_fractional(void);
void test_handle_set_difficulty_zero_rejected(void);
void test_handle_set_difficulty_negative_rejected(void);
void test_handle_set_difficulty_large_finite_accepted(void);
void test_handle_notify_golden(void);
void test_handle_notify_clean_jobs_false(void);
void test_handle_notify_invalid_too_few_fields(void);
void test_handle_notify_wrong_type_for_version(void);
void test_handle_notify_ta186_non_monotonic_job_id(void);
void test_build_configure_null_buf(void);
void test_build_configure_zero_size(void);
void test_build_subscribe_null_buf(void);
void test_build_subscribe_zero_size(void);
void test_build_authorize_null_buf(void);
void test_build_authorize_zero_size(void);
void test_build_authorize_null_wallet(void);
void test_build_authorize_null_worker(void);
void test_build_authorize_null_pass(void);
void test_build_keepalive_null_buf(void);
void test_build_keepalive_zero_size(void);
void test_handle_configure_null_state(void);
void test_handle_configure_null_result(void);
void test_handle_subscribe_null_state(void);
void test_handle_subscribe_null_result(void);
void test_handle_subscribe_missing_extranonce_field(void);
void test_handle_set_difficulty_null_state(void);
void test_handle_set_difficulty_null_params(void);
void test_handle_set_difficulty_not_array(void);
void test_handle_set_difficulty_empty_array(void);
void test_handle_set_difficulty_wrong_type(void);
void test_handle_notify_null_state(void);
void test_handle_notify_null_params(void);
void test_handle_notify_missing_field_at_index_0(void);
void test_handle_set_extranonce_valid_round_trip(void);
void test_handle_set_extranonce_not_array(void);
void test_handle_set_extranonce_array_too_short(void);
void test_handle_set_extranonce_en1_not_string(void);
void test_handle_set_extranonce_en1_too_long(void);
void test_handle_set_extranonce_en2_not_number(void);
void test_handle_set_extranonce_en2_negative(void);
void test_handle_set_extranonce_en2_too_large(void);

// test_stratum_reject.c
void test_parse_error_code_array_form_21(void);
void test_parse_error_code_array_form_23(void);
void test_parse_error_code_object_form_22(void);
void test_parse_error_code_object_form_25(void);
void test_parse_error_code_empty_array(void);
void test_parse_error_code_no_code_field(void);
void test_parse_error_code_null_recorder(void);
void test_classify_reject_job_not_found(void);
void test_classify_reject_duplicate(void);
void test_classify_reject_low_difficulty(void);
void test_classify_reject_stale_prevhash(void);
void test_classify_reject_unknown_code(void);

// test_stratum_fsm.c
void test_stratum_fsm_initial_state_is_disconnected(void);
void test_stratum_fsm_backoff_elapsed_drives_connect(void);
void test_stratum_fsm_full_happy_path_to_running(void);
void test_stratum_fsm_tcp_connect_failure_tears_down(void);
void test_stratum_fsm_job_received_self_loop_publishes_work(void);
void test_stratum_fsm_set_difficulty_republishes_work_when_job_staged(void);
void test_stratum_fsm_set_difficulty_no_publish_when_no_job_staged(void);
void test_stratum_fsm_share_submitted_drains_and_sends(void);
void test_stratum_fsm_reconnect_requested_from_running_tears_down(void);
void test_stratum_fsm_io_error_during_subscribe_tears_down(void);
void test_stratum_fsm_authorize_rejected_tears_down(void);
void test_stratum_fsm_teardown_is_single_funnel_from_every_failure_path(void);
void test_stratum_fsm_backoff_bumps_on_bare_connect_failure_not_reset(void);
void test_stratum_fsm_backoff_caps_at_30s_across_repeated_failures(void);
void test_stratum_fsm_backoff_resets_only_on_successful_handshake(void);
void test_stratum_fsm_job_drought_tears_down_after_five_minutes(void);
void test_stratum_fsm_job_received_resets_drought_clock(void);
void test_stratum_fsm_share_drought_tears_down_after_thirty_minutes(void);
void test_stratum_fsm_keepalive_fires_after_ninety_seconds(void);
void test_stratum_fsm_keepalive_suppressed_by_recent_tx_then_fires_after_idle(void);
void test_stratum_fsm_keepalive_ack_does_not_inflate_share_counters(void);
void test_stratum_fsm_unregistered_id_response_counts_as_submit(void);

// test_stratum_isolation.c
void test_stratum_isolation_service_never_blocks_when_connect_permanently_fails(void);
void test_stratum_isolation_service_never_blocks_when_pool_hangs_mid_session(void);
void test_stratum_isolation_service_touches_nothing_outside_its_own_ctx(void);

// test_stratum_json_ingest.c
void test_json_ingest_worst_case_notify_fits_default_pool(void);
void test_json_ingest_smaller_pool_fails_cleanly_on_oversized_document(void);
void test_json_ingest_malformed_line_fails_cleanly(void);
void test_json_ingest_truncated_line_fails_cleanly(void);
void test_json_ingest_clean_jobs_absent_defaults_false(void);
void test_json_ingest_clean_jobs_present_false_is_distinct_from_absent(void);

// test_tm_pool_config.c
void test_tm_pool_config_init_returns_ok(void);
void test_tm_pool_config_set_then_get_round_trip_slot0(void);
void test_tm_pool_config_set_then_get_round_trip_slot2(void);
void test_tm_pool_config_get_unset_slot_returns_ok_with_defaults(void);
void test_tm_pool_config_is_configured_false_on_unset_slot(void);
void test_tm_pool_config_is_configured_true_after_full_set(void);
void test_tm_pool_config_is_configured_false_when_port_zero(void);
void test_tm_pool_config_is_configured_false_when_worker_empty(void);
void test_tm_pool_config_set_slot1_does_not_touch_slot0_or_slot2(void);
void test_tm_pool_config_get_rejects_out_of_range_idx(void);
void test_tm_pool_config_set_rejects_out_of_range_idx(void);
void test_tm_pool_config_is_configured_false_for_out_of_range_idx(void);
void test_tm_pool_config_get_rejects_null_out(void);
void test_tm_pool_config_set_rejects_null_cfg(void);
void test_tm_pool_config_sv2_key_round_trips_when_set(void);
void test_tm_pool_config_sv2_key_absent_when_unset(void);
void test_tm_pool_config_sv2_key_cleared_by_reset_to_unset(void);
void test_tm_pool_config_sv2_key_set_true_with_empty_string_normalizes_to_erased(void);
void test_tm_pool_config_get_propagates_genuine_backend_fault(void);
void test_tm_pool_config_set_stops_at_first_failing_field(void);
void test_tm_pool_config_is_configured_false_on_genuine_backend_fault(void);
void test_tm_pool_config_set_partial_write_on_mid_sequence_fault_is_v1_parity(void);

// test_tm_pool_stats.c
void test_tm_pool_stats_record_share_updates_shares_best_diff_and_last_seen(void);
void test_tm_pool_stats_record_share_best_diff_only_advances_on_improvement(void);
void test_tm_pool_stats_record_share_rejects_null_share(void);
void test_tm_pool_stats_record_hashes_accumulates(void);
void test_tm_pool_stats_record_block_increments_blocks_and_last_seen(void);
void test_tm_pool_stats_switching_active_slot_flushes_prior_dirty_slot(void);
void test_tm_pool_stats_record_hashes_dirties_but_does_not_persist_until_flush(void);
void test_tm_pool_stats_flush_on_inactive_slot_is_a_noop(void);
void test_tm_pool_stats_switch_flush_failure_propagates_and_preserves_dirty_slot_for_retry(void);
void test_tm_pool_stats_round_trips_after_flush(void);
void test_tm_pool_stats_load_unset_slot_returns_zeroed_record(void);
void test_tm_pool_stats_reset_zeroes_ram_and_nvs_for_active_slot(void);
void test_tm_pool_stats_reset_zeroes_nvs_for_inactive_slot(void);
void test_tm_pool_stats_reset_partial_erase_failure_leaves_storage_split_ram_untouched_retry_recovers(void);
void test_tm_pool_stats_sanitize_rejects_nan_best_diff(void);
void test_tm_pool_stats_sanitize_rejects_inf_best_diff(void);
void test_tm_pool_stats_sanitize_rejects_zero_hash_clamp_sentinel(void);
void test_tm_pool_stats_sanitize_caps_blocks_found(void);
void test_tm_pool_stats_sanitize_out_of_window_timestamp_does_not_cascade(void);
void test_tm_pool_stats_sanitize_out_of_window_best_diff_ts_resets_only_itself(void);
void test_tm_pool_stats_sanitize_accepts_zero_timestamps(void);
void test_tm_pool_stats_sanitize_null_is_a_noop(void);
void test_tm_pool_stats_load_sanitizes_corrupt_stored_record(void);
void test_tm_pool_stats_load_propagates_genuine_backend_fault(void);
void test_tm_pool_stats_flush_propagates_genuine_backend_fault(void);
void test_tm_pool_stats_record_share_best_diff_flush_propagates_genuine_backend_fault(void);
void test_tm_pool_stats_load_rejects_out_of_range_idx(void);
void test_tm_pool_stats_load_rejects_null_out(void);
void test_tm_pool_stats_record_share_rejects_out_of_range_idx(void);
void test_tm_pool_stats_record_hashes_rejects_out_of_range_idx(void);
void test_tm_pool_stats_record_block_rejects_out_of_range_idx(void);
void test_tm_pool_stats_flush_rejects_out_of_range_idx(void);
void test_tm_pool_stats_reset_rejects_out_of_range_idx(void);

// test_tm_pool_scoreboard.c
void test_tm_pool_scoreboard_maybe_insert_empty_board_inserts(void);
void test_tm_pool_scoreboard_maybe_insert_ascending_sequence_keeps_sorted_desc(void);
void test_tm_pool_scoreboard_maybe_insert_descending_sequence_keeps_sorted_desc(void);
void test_tm_pool_scoreboard_maybe_insert_random_sequence_keeps_sorted_desc(void);
void test_tm_pool_scoreboard_maybe_insert_beats_min_evicts_min(void);
void test_tm_pool_scoreboard_maybe_insert_below_full_board_min_rejected(void);
void test_tm_pool_scoreboard_maybe_insert_exact_n_boundary(void);
void test_tm_pool_scoreboard_maybe_insert_hash_null_prefix_invalid(void);
void test_tm_pool_scoreboard_maybe_insert_hash_prefix_correct_msb_bytes(void);
void test_tm_pool_scoreboard_maybe_insert_job_id_truncated(void);
void test_tm_pool_scoreboard_maybe_insert_extranonce2_len_clamped(void);
void test_tm_pool_scoreboard_maybe_insert_null_extranonce2_forces_len_zero(void);
void test_tm_pool_scoreboard_maybe_insert_null_sb_returns_false(void);
void test_tm_pool_scoreboard_maybe_insert_null_share_returns_false(void);
void test_tm_pool_stats_record_share_full_round_trip_scoreboard(void);
void test_tm_pool_stats_record_share_scoreboard_change_persists_immediately(void);
void test_tm_pool_scoreboard_flushed_on_slot_switch(void);
void test_tm_pool_stats_record_share_score_flush_failure_leaves_dirty_for_retry(void);
void test_tm_pool_stats_switch_score_flush_failure_propagates_and_preserves_dirty_slot(void);
void test_tm_pool_stats_record_share_lifetime_flush_fault_does_not_block_scoreboard_flush(void);
void test_tm_pool_scoreboard_sanitize_drops_corrupt_entry_and_recompacts(void);
void test_tm_pool_scoreboard_sanitize_clamps_count_to_max(void);
void test_tm_pool_scoreboard_sanitize_clamps_extranonce2_len(void);
void test_tm_pool_scoreboard_sanitize_null_is_a_noop(void);
void test_tm_pool_scoreboard_sanitize_rejects_inf_diff(void);
void test_tm_pool_stats_load_sanitizes_corrupt_stored_scoreboard(void);
void test_tm_pool_scoreboard_hash_to_hex_known_prefix_reverses_to_big_endian(void);
void test_tm_pool_scoreboard_hash_to_hex_invalid_prefix_rejected(void);
void test_tm_pool_scoreboard_hash_to_hex_short_buffer_rejected(void);
void test_tm_pool_scoreboard_hash_to_hex_null_entry_rejected(void);
void test_tm_pool_scoreboard_hash_to_hex_null_out_rejected(void);
void test_tm_pool_scoreboard_load_propagates_genuine_backend_fault(void);
void test_tm_pool_scoreboard_load_rejects_out_of_range_idx(void);
void test_tm_pool_scoreboard_load_rejects_null_out(void);

void setUp(void) {}
void tearDown(void) {}

int main(void)
{
    UNITY_BEGIN();
    RUN_TEST(test_sha256_empty_string);
    RUN_TEST(test_sha256_abc);
    RUN_TEST(test_sha256_two_blocks);
    RUN_TEST(test_sha256d_known);
    RUN_TEST(test_sha256_midstate);
    RUN_TEST(test_sha256_genesis_header);
    RUN_TEST(test_sha256_transform_words);
    RUN_TEST(test_sha256_transform_performance);
    RUN_TEST(test_sha256_build_abc_block);
    RUN_TEST(test_sha256_sw_self_test_passes);
    RUN_TEST(test_mining_self_test_flag_default_false);
    RUN_TEST(test_mining_set_self_test_failed_flips_flag);
    RUN_TEST(test_sha256_check_abc_vector_accepts_correct_digest);
    RUN_TEST(test_sha256_check_abc_vector_rejects_wrong_digest);
    RUN_TEST(test_sha256_check_abc_vector_rejects_one_byte_flip);
    RUN_TEST(test_mining_get_sha_overlap_state_default_unknown);
    RUN_TEST(test_mining_set_sha_overlap_safe_true_sets_safe);
    RUN_TEST(test_mining_set_sha_overlap_safe_false_sets_unsafe);
    RUN_TEST(test_mining_get_sha_hwrite_state_default_unknown);
    RUN_TEST(test_mining_set_sha_hwrite_safe_true_sets_safe);
    RUN_TEST(test_mining_set_sha_hwrite_safe_false_sets_unsafe);
    RUN_TEST(test_share_meets_network_target_genesis_block);
    RUN_TEST(test_share_meets_network_target_pool_share_fails);
    RUN_TEST(test_share_meets_network_target_exact_equals_target);
    RUN_TEST(test_share_meets_network_target_known_hit);
    RUN_TEST(test_share_meets_network_target_share_misses_network);
    RUN_TEST(test_share_meets_network_target_pool_diff_not_network);
    RUN_TEST(test_share_validate_invalid_target_rejects);
    RUN_TEST(test_share_validate_below_target_misses);
    RUN_TEST(test_share_validate_low_difficulty_just_under_floor_rejects);
    RUN_TEST(test_share_validate_low_difficulty_at_floor_accepts);
    RUN_TEST(test_share_validate_clean_valid_accept);
    RUN_TEST(test_mining_hash_from_state_abc_vector);
    RUN_TEST(test_mining_hash_from_state_zero);
    RUN_TEST(test_serialize_header_genesis);
    RUN_TEST(test_set_header_nonce);
    RUN_TEST(test_nbits_to_target_genesis);
    RUN_TEST(test_nbits_to_target_high_diff);
    RUN_TEST(test_meets_target_pass);
    RUN_TEST(test_meets_target_fail);
    RUN_TEST(test_meets_target_equal);
    RUN_TEST(test_build_coinbase_hash);
    RUN_TEST(test_build_merkle_root_no_branches);
    RUN_TEST(test_build_merkle_root_with_branches);
    RUN_TEST(test_decode_stratum_prevhash);
    RUN_TEST(test_decode_stratum_prevhash_truncated);
    RUN_TEST(test_block1_full_pipeline);
    RUN_TEST(test_block170_merkle_and_hash);
    RUN_TEST(test_decode_stratum_prevhash_real);
    RUN_TEST(test_stratum_pipeline_block1);
    RUN_TEST(test_difficulty_to_target_diff1);
    RUN_TEST(test_difficulty_to_target_easy);
    RUN_TEST(test_difficulty_to_target_hard);
    RUN_TEST(test_mining_round_trip_block1);
    RUN_TEST(test_mining_early_reject_byte_order);
    RUN_TEST(test_difficulty_target_meets_target_integration);
    RUN_TEST(test_version_rolling_mask_increment);
    RUN_TEST(test_difficulty_to_target_nan);
    RUN_TEST(test_difficulty_to_target_inf);
    RUN_TEST(test_difficulty_to_target_neg_inf);
    RUN_TEST(test_difficulty_to_target_negative);
    RUN_TEST(test_difficulty_to_target_zero);
    RUN_TEST(test_difficulty_to_target_tiny);
    RUN_TEST(test_difficulty_to_target_normal);
    RUN_TEST(test_build_work_block1_pipeline);
    RUN_TEST(test_build_work_extranonce2_hex_and_coinbase);
    RUN_TEST(test_build_work_rejects_null_job);
    RUN_TEST(test_build_work_rejects_null_out);
    RUN_TEST(test_build_work_rejects_null_extranonce1_with_nonzero_len);
    RUN_TEST(test_build_work_rejects_oversized_extranonce2);
    RUN_TEST(test_is_target_valid_all_zero);

    RUN_TEST(test_is_target_valid_all_ff);
    RUN_TEST(test_is_target_valid_nonzero_msb31);
    RUN_TEST(test_is_target_valid_nonzero_msb30);
    RUN_TEST(test_is_target_valid_diff1);
    RUN_TEST(test_is_target_valid_diff512);
    RUN_TEST(test_is_target_valid_diff_001);
    RUN_TEST(test_package_result_round_trip_no_rolling);
    RUN_TEST(test_package_result_round_trip_with_rolling);
    RUN_TEST(test_avg_nan_safe_empty_all_nan);
    RUN_TEST(test_avg_nan_safe_single_value);
    RUN_TEST(test_avg_nan_safe_partial_nan);
    RUN_TEST(test_avg_nan_safe_all_populated);
    RUN_TEST(test_update_warmup_1m);
    RUN_TEST(test_update_full_1m_window);
    RUN_TEST(test_update_step_change);
    RUN_TEST(test_update_ring_wraparound);
    RUN_TEST(test_update_10m_blend_formula);
    RUN_TEST(test_update_1h_accumulation);
    RUN_TEST(test_update_with_zero_samples);
    RUN_TEST(test_update_mixed_values);
    RUN_TEST(test_mining_pool_eff_tick_zero_delta);
    RUN_TEST(test_mining_pool_eff_tick_typical);
    RUN_TEST(test_mining_pool_eff_tick_sum_decrease_clamps_to_zero);
    RUN_TEST(test_sw_backend_finds_block1_share);
    RUN_TEST(test_sw_backend_early_reject_low_diff);
    RUN_TEST(test_sw_backend_early_reject_high_diff);
    RUN_TEST(test_mine_nonce_range_counts);
    RUN_TEST(test_mine_nonce_range_stops_on_hit);
    RUN_TEST(test_mine_nonce_range_no_hit);
    RUN_TEST(test_mine_result_has_version_hex);
    RUN_TEST(test_pack_target_word0_diff1);
    RUN_TEST(test_pack_target_word0_easy_diff);
    RUN_TEST(test_pack_target_word0_hard_diff);
    RUN_TEST(test_build_block2_padding);
    RUN_TEST(test_package_result_no_version_rolling);
    RUN_TEST(test_package_result_version_rolling_submits_ver_bits);
    RUN_TEST(test_version_roll_stays_within_issue606_mask);
    RUN_TEST(test_header_rebuild_preserves_fixed_bit_issue606);
    RUN_TEST(test_mining_compute_pool_effective_hps_empty);
    RUN_TEST(test_mining_compute_pool_effective_hps_uptime_too_short);
    RUN_TEST(test_mining_compute_pool_effective_hps_typical);
    RUN_TEST(test_mining_compute_pool_effective_hps_diff1_share);
    RUN_TEST(test_mining_compute_pool_effective_hps_divide_by_zero_guard);
    RUN_TEST(test_mining_get_pool_effective_hashrate_host_stub);
    RUN_TEST(test_mining_get_pool_effective_rolling_host_stubs);
    RUN_TEST(test_pack_target_word0_exact_byte_order);
    RUN_TEST(test_share_reverify_block1_nonce);
    RUN_TEST(test_share_reverify_version_rolling);
    RUN_TEST(test_mining_efficiency_jth_known_case);
    RUN_TEST(test_mining_efficiency_jth_zero_hashrate);
    RUN_TEST(test_mining_efficiency_jth_negative_hashrate);
    RUN_TEST(test_mining_efficiency_jth_zero_power);
    RUN_TEST(test_mining_efficiency_jth_negative_power);
    RUN_TEST(test_mining_efficiency_jth_inverse_hashrate_scaling);
    RUN_TEST(test_sw_hash_nonce_rejects_over_target);
    RUN_TEST(test_block_found_cb_fires);
    RUN_TEST(test_block_found_cb_null_safe);
    RUN_TEST(test_mining_work_peek_default_false);
    RUN_TEST(test_mining_result_post_default_false);
    RUN_TEST(test_mining_queue_ops_bound_dispatches);
    RUN_TEST(test_mining_pause_gate_default_false);
    RUN_TEST(test_mining_pause_gate_bound);
    RUN_TEST(test_pool_stats_find_returns_existing_slot);
    RUN_TEST(test_pool_stats_case_insensitive_host_match);
    RUN_TEST(test_pool_stats_different_port_is_new_slot);
    RUN_TEST(test_pool_stats_alloc_into_empty_slot);
    RUN_TEST(test_pool_stats_lru_eviction_picks_lowest_last_seen);
    RUN_TEST(test_pool_stats_lru_eviction_skips_recent_slot);
    RUN_TEST(test_pool_stats_record_share_updates_matching_slot);
    RUN_TEST(test_pool_stats_record_block_increments_matching_slot);
    RUN_TEST(test_pool_stats_lifetime_blocks_survive_eviction);
    RUN_TEST(test_pool_stats_record_hashes_accumulates);
    RUN_TEST(test_pool_stats_null_slot_is_safe);
    RUN_TEST(test_pool_stats_slot_out_of_range_returns_null);
    RUN_TEST(test_pool_stats_find_or_alloc_null_host);
    RUN_TEST(test_pool_stats_init_runs_clean);
    RUN_TEST(test_pool_stats_reset_zeroes_all_state);
    RUN_TEST(test_mining_hotloop_finds_known_share);
    RUN_TEST(test_mining_hotloop_rejects_non_matching_nonce);
    RUN_TEST(test_mining_gather_unseeded_is_zeroed);
    RUN_TEST(test_mining_gather_round_trips_seeded_snapshot);
    RUN_TEST(test_mining_gather_round_trips_sha_self_test_failed_true);
    RUN_TEST(test_mining_gather_null_out_is_safe);
    RUN_TEST(test_mining_desc_snap_size_matches_struct);
    RUN_TEST(test_mining_desc_find_known_key);
    RUN_TEST(test_mining_desc_find_unknown_key);
    RUN_TEST(test_mining_desc_walk_matches_seeded_snapshot);
    RUN_TEST(test_stratum_backoff_init);
    RUN_TEST(test_stratum_backoff_first_fail_sleeps_initial_then_doubles);
    RUN_TEST(test_stratum_backoff_progression_doubles_to_cap);
    RUN_TEST(test_stratum_backoff_caps_at_30s);
    RUN_TEST(test_stratum_backoff_reset_on_success);
    RUN_TEST(test_stratum_backoff_reset_restarts_doubling);
    RUN_TEST(test_stratum_reqid_register_then_take);
    RUN_TEST(test_stratum_reqid_take_consumes);
    RUN_TEST(test_stratum_reqid_unregistered_id_returns_none);
    RUN_TEST(test_stratum_reqid_keepalive_survives_a_newer_overwrite);
    RUN_TEST(test_stratum_reqid_table_full_evicts_oldest);
    RUN_TEST(test_stratum_reqid_reset_clears_table);
    RUN_TEST(test_stratum_machine_build_configure);
    RUN_TEST(test_stratum_machine_build_configure_truncation);
    RUN_TEST(test_stratum_machine_build_subscribe);
    RUN_TEST(test_stratum_machine_build_subscribe_truncation);
    RUN_TEST(test_stratum_machine_build_authorize);
    RUN_TEST(test_stratum_machine_build_authorize_different_values);
    RUN_TEST(test_stratum_machine_build_authorize_truncation);
    RUN_TEST(test_stratum_machine_build_keepalive);
    RUN_TEST(test_stratum_machine_build_keepalive_small_difficulty);
    RUN_TEST(test_stratum_machine_build_keepalive_large_difficulty);
    RUN_TEST(test_stratum_machine_build_keepalive_truncation);
    RUN_TEST(test_handle_configure_result_golden);
    RUN_TEST(test_handle_configure_result_missing_field);
    RUN_TEST(test_handle_configure_result_pool_not_supported);
    RUN_TEST(test_handle_configure_result_narrow_mask_issue606);
    RUN_TEST(test_handle_subscribe_result_golden);
    RUN_TEST(test_handle_subscribe_result_too_long_extranonce1);
    RUN_TEST(test_handle_subscribe_result_invalid_no_extranonce);
    RUN_TEST(test_handle_subscribe_result_extranonce2_size_at_max_accepted);
    RUN_TEST(test_handle_subscribe_result_extranonce2_size_over_max_rejected);
    RUN_TEST(test_handle_subscribe_result_extranonce2_size_negative_rejected);
    RUN_TEST(test_handle_set_difficulty_1);
    RUN_TEST(test_handle_set_difficulty_65536);
    RUN_TEST(test_handle_set_difficulty_fractional);
    RUN_TEST(test_handle_set_difficulty_zero_rejected);
    RUN_TEST(test_handle_set_difficulty_negative_rejected);
    RUN_TEST(test_handle_set_difficulty_large_finite_accepted);
    RUN_TEST(test_handle_notify_golden);
    RUN_TEST(test_handle_notify_clean_jobs_false);
    RUN_TEST(test_handle_notify_invalid_too_few_fields);
    RUN_TEST(test_handle_notify_wrong_type_for_version);
    RUN_TEST(test_handle_notify_ta186_non_monotonic_job_id);
    RUN_TEST(test_build_configure_null_buf);
    RUN_TEST(test_build_configure_zero_size);
    RUN_TEST(test_build_subscribe_null_buf);
    RUN_TEST(test_build_subscribe_zero_size);
    RUN_TEST(test_build_authorize_null_buf);
    RUN_TEST(test_build_authorize_zero_size);
    RUN_TEST(test_build_authorize_null_wallet);
    RUN_TEST(test_build_authorize_null_worker);
    RUN_TEST(test_build_authorize_null_pass);
    RUN_TEST(test_build_keepalive_null_buf);
    RUN_TEST(test_build_keepalive_zero_size);
    RUN_TEST(test_handle_configure_null_state);
    RUN_TEST(test_handle_configure_null_result);
    RUN_TEST(test_handle_subscribe_null_state);
    RUN_TEST(test_handle_subscribe_null_result);
    RUN_TEST(test_handle_subscribe_missing_extranonce_field);
    RUN_TEST(test_handle_set_difficulty_null_state);
    RUN_TEST(test_handle_set_difficulty_null_params);
    RUN_TEST(test_handle_set_difficulty_not_array);
    RUN_TEST(test_handle_set_difficulty_empty_array);
    RUN_TEST(test_handle_set_difficulty_wrong_type);
    RUN_TEST(test_handle_notify_null_state);
    RUN_TEST(test_handle_notify_null_params);
    RUN_TEST(test_handle_notify_missing_field_at_index_0);
    RUN_TEST(test_handle_set_extranonce_valid_round_trip);
    RUN_TEST(test_handle_set_extranonce_not_array);
    RUN_TEST(test_handle_set_extranonce_array_too_short);
    RUN_TEST(test_handle_set_extranonce_en1_not_string);
    RUN_TEST(test_handle_set_extranonce_en1_too_long);
    RUN_TEST(test_handle_set_extranonce_en2_not_number);
    RUN_TEST(test_handle_set_extranonce_en2_negative);
    RUN_TEST(test_handle_set_extranonce_en2_too_large);
    RUN_TEST(test_parse_error_code_array_form_21);
    RUN_TEST(test_parse_error_code_array_form_23);
    RUN_TEST(test_parse_error_code_object_form_22);
    RUN_TEST(test_parse_error_code_object_form_25);
    RUN_TEST(test_parse_error_code_empty_array);
    RUN_TEST(test_parse_error_code_no_code_field);
    RUN_TEST(test_parse_error_code_null_recorder);
    RUN_TEST(test_classify_reject_job_not_found);
    RUN_TEST(test_classify_reject_duplicate);
    RUN_TEST(test_classify_reject_low_difficulty);
    RUN_TEST(test_classify_reject_stale_prevhash);
    RUN_TEST(test_classify_reject_unknown_code);
    RUN_TEST(test_stratum_fsm_initial_state_is_disconnected);
    RUN_TEST(test_stratum_fsm_backoff_elapsed_drives_connect);
    RUN_TEST(test_stratum_fsm_full_happy_path_to_running);
    RUN_TEST(test_stratum_fsm_tcp_connect_failure_tears_down);
    RUN_TEST(test_stratum_fsm_job_received_self_loop_publishes_work);
    RUN_TEST(test_stratum_fsm_set_difficulty_republishes_work_when_job_staged);
    RUN_TEST(test_stratum_fsm_set_difficulty_no_publish_when_no_job_staged);
    RUN_TEST(test_stratum_fsm_share_submitted_drains_and_sends);
    RUN_TEST(test_stratum_fsm_reconnect_requested_from_running_tears_down);
    RUN_TEST(test_stratum_fsm_io_error_during_subscribe_tears_down);
    RUN_TEST(test_stratum_fsm_authorize_rejected_tears_down);
    RUN_TEST(test_stratum_fsm_teardown_is_single_funnel_from_every_failure_path);
    RUN_TEST(test_stratum_fsm_backoff_bumps_on_bare_connect_failure_not_reset);
    RUN_TEST(test_stratum_fsm_backoff_caps_at_30s_across_repeated_failures);
    RUN_TEST(test_stratum_fsm_backoff_resets_only_on_successful_handshake);
    RUN_TEST(test_stratum_fsm_job_drought_tears_down_after_five_minutes);
    RUN_TEST(test_stratum_fsm_job_received_resets_drought_clock);
    RUN_TEST(test_stratum_fsm_share_drought_tears_down_after_thirty_minutes);
    RUN_TEST(test_stratum_fsm_keepalive_fires_after_ninety_seconds);
    RUN_TEST(test_stratum_fsm_keepalive_suppressed_by_recent_tx_then_fires_after_idle);
    RUN_TEST(test_stratum_fsm_keepalive_ack_does_not_inflate_share_counters);
    RUN_TEST(test_stratum_fsm_unregistered_id_response_counts_as_submit);
    RUN_TEST(test_stratum_isolation_service_never_blocks_when_connect_permanently_fails);
    RUN_TEST(test_stratum_isolation_service_never_blocks_when_pool_hangs_mid_session);
    RUN_TEST(test_stratum_isolation_service_touches_nothing_outside_its_own_ctx);
    RUN_TEST(test_json_ingest_worst_case_notify_fits_default_pool);
    RUN_TEST(test_json_ingest_smaller_pool_fails_cleanly_on_oversized_document);
    RUN_TEST(test_json_ingest_malformed_line_fails_cleanly);
    RUN_TEST(test_json_ingest_truncated_line_fails_cleanly);
    RUN_TEST(test_json_ingest_clean_jobs_absent_defaults_false);
    RUN_TEST(test_json_ingest_clean_jobs_present_false_is_distinct_from_absent);
    RUN_TEST(test_tm_pool_config_init_returns_ok);
    RUN_TEST(test_tm_pool_config_set_then_get_round_trip_slot0);
    RUN_TEST(test_tm_pool_config_set_then_get_round_trip_slot2);
    RUN_TEST(test_tm_pool_config_get_unset_slot_returns_ok_with_defaults);
    RUN_TEST(test_tm_pool_config_is_configured_false_on_unset_slot);
    RUN_TEST(test_tm_pool_config_is_configured_true_after_full_set);
    RUN_TEST(test_tm_pool_config_is_configured_false_when_port_zero);
    RUN_TEST(test_tm_pool_config_is_configured_false_when_worker_empty);
    RUN_TEST(test_tm_pool_config_set_slot1_does_not_touch_slot0_or_slot2);
    RUN_TEST(test_tm_pool_config_get_rejects_out_of_range_idx);
    RUN_TEST(test_tm_pool_config_set_rejects_out_of_range_idx);
    RUN_TEST(test_tm_pool_config_is_configured_false_for_out_of_range_idx);
    RUN_TEST(test_tm_pool_config_get_rejects_null_out);
    RUN_TEST(test_tm_pool_config_set_rejects_null_cfg);
    RUN_TEST(test_tm_pool_config_sv2_key_round_trips_when_set);
    RUN_TEST(test_tm_pool_config_sv2_key_absent_when_unset);
    RUN_TEST(test_tm_pool_config_sv2_key_cleared_by_reset_to_unset);
    RUN_TEST(test_tm_pool_config_sv2_key_set_true_with_empty_string_normalizes_to_erased);
    RUN_TEST(test_tm_pool_config_get_propagates_genuine_backend_fault);
    RUN_TEST(test_tm_pool_config_set_stops_at_first_failing_field);
    RUN_TEST(test_tm_pool_config_is_configured_false_on_genuine_backend_fault);
    RUN_TEST(test_tm_pool_config_set_partial_write_on_mid_sequence_fault_is_v1_parity);
    RUN_TEST(test_tm_pool_stats_record_share_updates_shares_best_diff_and_last_seen);
    RUN_TEST(test_tm_pool_stats_record_share_best_diff_only_advances_on_improvement);
    RUN_TEST(test_tm_pool_stats_record_share_rejects_null_share);
    RUN_TEST(test_tm_pool_stats_record_hashes_accumulates);
    RUN_TEST(test_tm_pool_stats_record_block_increments_blocks_and_last_seen);
    RUN_TEST(test_tm_pool_stats_switching_active_slot_flushes_prior_dirty_slot);
    RUN_TEST(test_tm_pool_stats_record_hashes_dirties_but_does_not_persist_until_flush);
    RUN_TEST(test_tm_pool_stats_flush_on_inactive_slot_is_a_noop);
    RUN_TEST(test_tm_pool_stats_switch_flush_failure_propagates_and_preserves_dirty_slot_for_retry);
    RUN_TEST(test_tm_pool_stats_round_trips_after_flush);
    RUN_TEST(test_tm_pool_stats_load_unset_slot_returns_zeroed_record);
    RUN_TEST(test_tm_pool_stats_reset_zeroes_ram_and_nvs_for_active_slot);
    RUN_TEST(test_tm_pool_stats_reset_zeroes_nvs_for_inactive_slot);
    RUN_TEST(test_tm_pool_stats_reset_partial_erase_failure_leaves_storage_split_ram_untouched_retry_recovers);
    RUN_TEST(test_tm_pool_stats_sanitize_rejects_nan_best_diff);
    RUN_TEST(test_tm_pool_stats_sanitize_rejects_inf_best_diff);
    RUN_TEST(test_tm_pool_stats_sanitize_rejects_zero_hash_clamp_sentinel);
    RUN_TEST(test_tm_pool_stats_sanitize_caps_blocks_found);
    RUN_TEST(test_tm_pool_stats_sanitize_out_of_window_timestamp_does_not_cascade);
    RUN_TEST(test_tm_pool_stats_sanitize_out_of_window_best_diff_ts_resets_only_itself);
    RUN_TEST(test_tm_pool_stats_sanitize_accepts_zero_timestamps);
    RUN_TEST(test_tm_pool_stats_sanitize_null_is_a_noop);
    RUN_TEST(test_tm_pool_stats_load_sanitizes_corrupt_stored_record);
    RUN_TEST(test_tm_pool_stats_load_propagates_genuine_backend_fault);
    RUN_TEST(test_tm_pool_stats_flush_propagates_genuine_backend_fault);
    RUN_TEST(test_tm_pool_stats_record_share_best_diff_flush_propagates_genuine_backend_fault);
    RUN_TEST(test_tm_pool_stats_load_rejects_out_of_range_idx);
    RUN_TEST(test_tm_pool_stats_load_rejects_null_out);
    RUN_TEST(test_tm_pool_stats_record_share_rejects_out_of_range_idx);
    RUN_TEST(test_tm_pool_stats_record_hashes_rejects_out_of_range_idx);
    RUN_TEST(test_tm_pool_stats_record_block_rejects_out_of_range_idx);
    RUN_TEST(test_tm_pool_stats_flush_rejects_out_of_range_idx);
    RUN_TEST(test_tm_pool_stats_reset_rejects_out_of_range_idx);
    RUN_TEST(test_tm_pool_scoreboard_maybe_insert_empty_board_inserts);
    RUN_TEST(test_tm_pool_scoreboard_maybe_insert_ascending_sequence_keeps_sorted_desc);
    RUN_TEST(test_tm_pool_scoreboard_maybe_insert_descending_sequence_keeps_sorted_desc);
    RUN_TEST(test_tm_pool_scoreboard_maybe_insert_random_sequence_keeps_sorted_desc);
    RUN_TEST(test_tm_pool_scoreboard_maybe_insert_beats_min_evicts_min);
    RUN_TEST(test_tm_pool_scoreboard_maybe_insert_below_full_board_min_rejected);
    RUN_TEST(test_tm_pool_scoreboard_maybe_insert_exact_n_boundary);
    RUN_TEST(test_tm_pool_scoreboard_maybe_insert_hash_null_prefix_invalid);
    RUN_TEST(test_tm_pool_scoreboard_maybe_insert_hash_prefix_correct_msb_bytes);
    RUN_TEST(test_tm_pool_scoreboard_maybe_insert_job_id_truncated);
    RUN_TEST(test_tm_pool_scoreboard_maybe_insert_extranonce2_len_clamped);
    RUN_TEST(test_tm_pool_scoreboard_maybe_insert_null_extranonce2_forces_len_zero);
    RUN_TEST(test_tm_pool_scoreboard_maybe_insert_null_sb_returns_false);
    RUN_TEST(test_tm_pool_scoreboard_maybe_insert_null_share_returns_false);
    RUN_TEST(test_tm_pool_stats_record_share_full_round_trip_scoreboard);
    RUN_TEST(test_tm_pool_stats_record_share_scoreboard_change_persists_immediately);
    RUN_TEST(test_tm_pool_scoreboard_flushed_on_slot_switch);
    RUN_TEST(test_tm_pool_stats_record_share_score_flush_failure_leaves_dirty_for_retry);
    RUN_TEST(test_tm_pool_stats_switch_score_flush_failure_propagates_and_preserves_dirty_slot);
    RUN_TEST(test_tm_pool_stats_record_share_lifetime_flush_fault_does_not_block_scoreboard_flush);
    RUN_TEST(test_tm_pool_scoreboard_sanitize_drops_corrupt_entry_and_recompacts);
    RUN_TEST(test_tm_pool_scoreboard_sanitize_clamps_count_to_max);
    RUN_TEST(test_tm_pool_scoreboard_sanitize_clamps_extranonce2_len);
    RUN_TEST(test_tm_pool_scoreboard_sanitize_null_is_a_noop);
    RUN_TEST(test_tm_pool_scoreboard_sanitize_rejects_inf_diff);
    RUN_TEST(test_tm_pool_stats_load_sanitizes_corrupt_stored_scoreboard);
    RUN_TEST(test_tm_pool_scoreboard_hash_to_hex_known_prefix_reverses_to_big_endian);
    RUN_TEST(test_tm_pool_scoreboard_hash_to_hex_invalid_prefix_rejected);
    RUN_TEST(test_tm_pool_scoreboard_hash_to_hex_short_buffer_rejected);
    RUN_TEST(test_tm_pool_scoreboard_hash_to_hex_null_entry_rejected);
    RUN_TEST(test_tm_pool_scoreboard_hash_to_hex_null_out_rejected);
    RUN_TEST(test_tm_pool_scoreboard_load_propagates_genuine_backend_fault);
    RUN_TEST(test_tm_pool_scoreboard_load_rejects_out_of_range_idx);
    RUN_TEST(test_tm_pool_scoreboard_load_rejects_null_out);
    return UNITY_END();
}
