// Host test harness entry point -- manual RUN_TEST() registration (no
// auto-discovery), per workspace convention. See test_stratum_*.c for the
// individual test files this pulls in.
#include <unity.h>

void setUp(void) {}
void tearDown(void) {}

void test_parse_error_code_array_form_21(void);
void test_parse_error_code_array_form_23(void);
void test_parse_error_code_object_form_22(void);
void test_parse_error_code_object_form_25(void);
void test_parse_error_code_empty_array(void);
void test_parse_error_code_no_code_field(void);
void test_classify_reject_job_not_found(void);
void test_classify_reject_duplicate(void);
void test_classify_reject_low_difficulty(void);
void test_classify_reject_stale_prevhash(void);
void test_classify_reject_unknown_code(void);
void test_stratum_backoff_init(void);
void test_stratum_backoff_first_fail_sleeps_initial_then_doubles(void);
void test_stratum_backoff_progression_doubles_to_cap(void);
void test_stratum_backoff_caps_at_30s(void);
void test_stratum_backoff_reset_on_success(void);
void test_stratum_backoff_reset_restarts_doubling(void);
void test_stratum_watchdog_job_drought_never_observed(void);
void test_stratum_watchdog_job_drought_below_threshold(void);
void test_stratum_watchdog_job_drought_at_threshold(void);
void test_stratum_watchdog_job_drought_above_threshold(void);
void test_stratum_watchdog_job_drought_wraparound(void);
void test_stratum_watchdog_share_drought_both_zero(void);
void test_stratum_watchdog_share_drought_only_last_share_below_threshold(void);
void test_stratum_watchdog_share_drought_session_start_at_threshold(void);
void test_stratum_watchdog_share_drought_only_last_share_above_threshold(void);
void test_stratum_watchdog_share_drought_prefers_last_share(void);
void test_stratum_watchdog_share_drought_falls_back_to_session_start(void);
void test_stratum_watchdog_share_drought_last_share_overrides_old_session(void);
void test_stratum_watchdog_keepalive_never_transmitted(void);
void test_stratum_watchdog_keepalive_below_threshold(void);
void test_stratum_watchdog_keepalive_at_threshold(void);
void test_stratum_watchdog_keepalive_above_threshold(void);
void test_stratum_watchdog_keepalive_wraparound(void);
void test_stratum_fsm_initial_state_is_disconnected(void);
void test_stratum_fsm_backoff_elapsed_drives_connect(void);
void test_stratum_fsm_full_happy_path_to_running(void);
void test_stratum_fsm_tcp_connect_failure_tears_down(void);
void test_stratum_fsm_job_received_self_loop_publishes_work(void);
void test_stratum_fsm_share_submitted_drains_and_sends(void);
void test_stratum_fsm_reconnect_requested_from_running_tears_down(void);
void test_stratum_fsm_io_error_during_subscribe_tears_down(void);
void test_stratum_fsm_authorize_rejected_tears_down(void);
void test_stratum_fsm_teardown_is_single_funnel_from_every_failure_path(void);
void test_stratum_fsm_backoff_bumps_on_bare_connect_failure_not_reset(void);
void test_stratum_fsm_backoff_caps_at_30s_across_repeated_failures(void);
void test_stratum_fsm_backoff_resets_only_on_successful_handshake(void);
void test_stratum_fsm_job_drought_tears_down_after_five_minutes(void);
void test_stratum_fsm_job_received_resets_drought_clock(void);
void test_stratum_fsm_share_drought_tears_down_after_thirty_minutes(void);
void test_stratum_fsm_keepalive_fires_after_ninety_seconds(void);
void test_stratum_fsm_keepalive_ack_does_not_inflate_share_counters(void);
void test_stratum_fsm_unregistered_id_response_counts_as_submit(void);
void test_stratum_fsm_service_never_blocks_a_co_running_task(void);
void test_stratum_machine_build_configure(void);
void test_stratum_machine_build_configure_truncation(void);
void test_stratum_machine_build_subscribe(void);
void test_stratum_machine_build_subscribe_truncation(void);
void test_stratum_machine_build_authorize(void);
void test_stratum_machine_build_authorize_different_values(void);
void test_stratum_machine_build_authorize_truncation(void);
void test_stratum_machine_build_keepalive(void);
void test_stratum_machine_build_keepalive_small_difficulty(void);
void test_stratum_machine_build_keepalive_large_difficulty(void);
void test_stratum_machine_build_keepalive_truncation(void);
void test_handle_configure_result_golden(void);
void test_handle_configure_result_missing_field(void);
void test_handle_configure_result_pool_not_supported(void);
void test_handle_subscribe_result_golden(void);
void test_handle_subscribe_result_too_long_extranonce1(void);
void test_handle_subscribe_result_invalid_no_extranonce(void);
void test_handle_set_difficulty_1(void);
void test_handle_set_difficulty_65536(void);
void test_handle_set_difficulty_fractional(void);
void test_handle_set_difficulty_zero_rejected(void);
void test_handle_set_difficulty_negative_rejected(void);
void test_handle_set_difficulty_large_finite_accepted(void);
void test_handle_notify_golden(void);
void test_handle_notify_clean_jobs_false(void);
void test_handle_notify_invalid_too_few_fields(void);
void test_handle_notify_wrong_type_for_version(void);
void test_handle_notify_ta186_non_monotonic_job_id(void);
void test_build_configure_null_buf(void);
void test_build_configure_zero_size(void);
void test_build_subscribe_null_buf(void);
void test_build_subscribe_zero_size(void);
void test_build_authorize_null_buf(void);
void test_build_authorize_zero_size(void);
void test_build_authorize_null_wallet(void);
void test_build_authorize_null_worker(void);
void test_build_authorize_null_pass(void);
void test_build_keepalive_null_buf(void);
void test_build_keepalive_zero_size(void);
void test_handle_configure_null_state(void);
void test_handle_configure_null_result(void);
void test_handle_subscribe_null_state(void);
void test_handle_subscribe_null_result(void);
void test_handle_subscribe_missing_extranonce_field(void);
void test_handle_set_difficulty_null_state(void);
void test_handle_set_difficulty_null_params(void);
void test_handle_set_difficulty_not_array(void);
void test_handle_set_difficulty_empty_array(void);
void test_handle_set_difficulty_wrong_type(void);
void test_handle_notify_null_state(void);
void test_handle_notify_null_params(void);
void test_handle_notify_missing_field_at_index_0(void);
void test_handle_set_extranonce_valid_round_trip(void);
void test_handle_set_extranonce_not_array(void);
void test_handle_set_extranonce_array_too_short(void);
void test_handle_set_extranonce_en1_not_string(void);
void test_handle_set_extranonce_en1_too_long(void);
void test_handle_set_extranonce_en2_not_number(void);
void test_handle_set_extranonce_en2_negative(void);
void test_handle_set_extranonce_en2_too_large(void);
void test_stratum_reqid_register_then_take(void);
void test_stratum_reqid_take_consumes(void);
void test_stratum_reqid_unregistered_id_returns_none(void);
void test_stratum_reqid_keepalive_survives_a_newer_overwrite(void);
void test_stratum_reqid_table_full_evicts_oldest(void);
void test_stratum_reqid_reset_clears_table(void);

int main(void)
{
    UNITY_BEGIN();
    RUN_TEST(test_parse_error_code_array_form_21);
    RUN_TEST(test_parse_error_code_array_form_23);
    RUN_TEST(test_parse_error_code_object_form_22);
    RUN_TEST(test_parse_error_code_object_form_25);
    RUN_TEST(test_parse_error_code_empty_array);
    RUN_TEST(test_parse_error_code_no_code_field);
    RUN_TEST(test_classify_reject_job_not_found);
    RUN_TEST(test_classify_reject_duplicate);
    RUN_TEST(test_classify_reject_low_difficulty);
    RUN_TEST(test_classify_reject_stale_prevhash);
    RUN_TEST(test_classify_reject_unknown_code);
    RUN_TEST(test_stratum_backoff_init);
    RUN_TEST(test_stratum_backoff_first_fail_sleeps_initial_then_doubles);
    RUN_TEST(test_stratum_backoff_progression_doubles_to_cap);
    RUN_TEST(test_stratum_backoff_caps_at_30s);
    RUN_TEST(test_stratum_backoff_reset_on_success);
    RUN_TEST(test_stratum_backoff_reset_restarts_doubling);
    RUN_TEST(test_stratum_watchdog_job_drought_never_observed);
    RUN_TEST(test_stratum_watchdog_job_drought_below_threshold);
    RUN_TEST(test_stratum_watchdog_job_drought_at_threshold);
    RUN_TEST(test_stratum_watchdog_job_drought_above_threshold);
    RUN_TEST(test_stratum_watchdog_job_drought_wraparound);
    RUN_TEST(test_stratum_watchdog_share_drought_both_zero);
    RUN_TEST(test_stratum_watchdog_share_drought_only_last_share_below_threshold);
    RUN_TEST(test_stratum_watchdog_share_drought_session_start_at_threshold);
    RUN_TEST(test_stratum_watchdog_share_drought_only_last_share_above_threshold);
    RUN_TEST(test_stratum_watchdog_share_drought_prefers_last_share);
    RUN_TEST(test_stratum_watchdog_share_drought_falls_back_to_session_start);
    RUN_TEST(test_stratum_watchdog_share_drought_last_share_overrides_old_session);
    RUN_TEST(test_stratum_watchdog_keepalive_never_transmitted);
    RUN_TEST(test_stratum_watchdog_keepalive_below_threshold);
    RUN_TEST(test_stratum_watchdog_keepalive_at_threshold);
    RUN_TEST(test_stratum_watchdog_keepalive_above_threshold);
    RUN_TEST(test_stratum_watchdog_keepalive_wraparound);
    RUN_TEST(test_stratum_fsm_initial_state_is_disconnected);
    RUN_TEST(test_stratum_fsm_backoff_elapsed_drives_connect);
    RUN_TEST(test_stratum_fsm_full_happy_path_to_running);
    RUN_TEST(test_stratum_fsm_tcp_connect_failure_tears_down);
    RUN_TEST(test_stratum_fsm_job_received_self_loop_publishes_work);
    RUN_TEST(test_stratum_fsm_share_submitted_drains_and_sends);
    RUN_TEST(test_stratum_fsm_reconnect_requested_from_running_tears_down);
    RUN_TEST(test_stratum_fsm_io_error_during_subscribe_tears_down);
    RUN_TEST(test_stratum_fsm_authorize_rejected_tears_down);
    RUN_TEST(test_stratum_fsm_teardown_is_single_funnel_from_every_failure_path);
    RUN_TEST(test_stratum_fsm_backoff_bumps_on_bare_connect_failure_not_reset);
    RUN_TEST(test_stratum_fsm_backoff_caps_at_30s_across_repeated_failures);
    RUN_TEST(test_stratum_fsm_backoff_resets_only_on_successful_handshake);
    RUN_TEST(test_stratum_fsm_job_drought_tears_down_after_five_minutes);
    RUN_TEST(test_stratum_fsm_job_received_resets_drought_clock);
    RUN_TEST(test_stratum_fsm_share_drought_tears_down_after_thirty_minutes);
    RUN_TEST(test_stratum_fsm_keepalive_fires_after_ninety_seconds);
    RUN_TEST(test_stratum_fsm_keepalive_ack_does_not_inflate_share_counters);
    RUN_TEST(test_stratum_fsm_unregistered_id_response_counts_as_submit);
    RUN_TEST(test_stratum_fsm_service_never_blocks_a_co_running_task);
    RUN_TEST(test_stratum_machine_build_configure);
    RUN_TEST(test_stratum_machine_build_configure_truncation);
    RUN_TEST(test_stratum_machine_build_subscribe);
    RUN_TEST(test_stratum_machine_build_subscribe_truncation);
    RUN_TEST(test_stratum_machine_build_authorize);
    RUN_TEST(test_stratum_machine_build_authorize_different_values);
    RUN_TEST(test_stratum_machine_build_authorize_truncation);
    RUN_TEST(test_stratum_machine_build_keepalive);
    RUN_TEST(test_stratum_machine_build_keepalive_small_difficulty);
    RUN_TEST(test_stratum_machine_build_keepalive_large_difficulty);
    RUN_TEST(test_stratum_machine_build_keepalive_truncation);
    RUN_TEST(test_handle_configure_result_golden);
    RUN_TEST(test_handle_configure_result_missing_field);
    RUN_TEST(test_handle_configure_result_pool_not_supported);
    RUN_TEST(test_handle_subscribe_result_golden);
    RUN_TEST(test_handle_subscribe_result_too_long_extranonce1);
    RUN_TEST(test_handle_subscribe_result_invalid_no_extranonce);
    RUN_TEST(test_handle_set_difficulty_1);
    RUN_TEST(test_handle_set_difficulty_65536);
    RUN_TEST(test_handle_set_difficulty_fractional);
    RUN_TEST(test_handle_set_difficulty_zero_rejected);
    RUN_TEST(test_handle_set_difficulty_negative_rejected);
    RUN_TEST(test_handle_set_difficulty_large_finite_accepted);
    RUN_TEST(test_handle_notify_golden);
    RUN_TEST(test_handle_notify_clean_jobs_false);
    RUN_TEST(test_handle_notify_invalid_too_few_fields);
    RUN_TEST(test_handle_notify_wrong_type_for_version);
    RUN_TEST(test_handle_notify_ta186_non_monotonic_job_id);
    RUN_TEST(test_build_configure_null_buf);
    RUN_TEST(test_build_configure_zero_size);
    RUN_TEST(test_build_subscribe_null_buf);
    RUN_TEST(test_build_subscribe_zero_size);
    RUN_TEST(test_build_authorize_null_buf);
    RUN_TEST(test_build_authorize_zero_size);
    RUN_TEST(test_build_authorize_null_wallet);
    RUN_TEST(test_build_authorize_null_worker);
    RUN_TEST(test_build_authorize_null_pass);
    RUN_TEST(test_build_keepalive_null_buf);
    RUN_TEST(test_build_keepalive_zero_size);
    RUN_TEST(test_handle_configure_null_state);
    RUN_TEST(test_handle_configure_null_result);
    RUN_TEST(test_handle_subscribe_null_state);
    RUN_TEST(test_handle_subscribe_null_result);
    RUN_TEST(test_handle_subscribe_missing_extranonce_field);
    RUN_TEST(test_handle_set_difficulty_null_state);
    RUN_TEST(test_handle_set_difficulty_null_params);
    RUN_TEST(test_handle_set_difficulty_not_array);
    RUN_TEST(test_handle_set_difficulty_empty_array);
    RUN_TEST(test_handle_set_difficulty_wrong_type);
    RUN_TEST(test_handle_notify_null_state);
    RUN_TEST(test_handle_notify_null_params);
    RUN_TEST(test_handle_notify_missing_field_at_index_0);
    RUN_TEST(test_handle_set_extranonce_valid_round_trip);
    RUN_TEST(test_handle_set_extranonce_not_array);
    RUN_TEST(test_handle_set_extranonce_array_too_short);
    RUN_TEST(test_handle_set_extranonce_en1_not_string);
    RUN_TEST(test_handle_set_extranonce_en1_too_long);
    RUN_TEST(test_handle_set_extranonce_en2_not_number);
    RUN_TEST(test_handle_set_extranonce_en2_negative);
    RUN_TEST(test_handle_set_extranonce_en2_too_large);
    RUN_TEST(test_stratum_reqid_register_then_take);
    RUN_TEST(test_stratum_reqid_take_consumes);
    RUN_TEST(test_stratum_reqid_unregistered_id_returns_none);
    RUN_TEST(test_stratum_reqid_keepalive_survives_a_newer_overwrite);
    RUN_TEST(test_stratum_reqid_table_full_evicts_oldest);
    RUN_TEST(test_stratum_reqid_reset_clears_table);
    return UNITY_END();
}
