#!/usr/bin/env python3
"""Convert SVG logo to RGB565 C array for the ST7735 display."""

import sys
import io
import cairosvg
from PIL import Image


def svg_to_rgb565(svg_path, out_path, size=56, color=(255, 191, 0)):
    # Read SVG and replace CSS variables with explicit colors
    with open(svg_path) as f:
        svg_text = f.read()
    svg_text = svg_text.replace("fill='currentColor'", "fill='white'")
    svg_text = svg_text.replace("fill='var(--bg)'", "fill='black'")

    # Render SVG to PNG in memory
    png_data = cairosvg.svg2png(
        bytestring=svg_text.encode(),
        output_width=size,
        output_height=size,
        background_color="black",
    )
    img = Image.open(io.BytesIO(png_data)).convert("RGB")

    # Convert to RGB565 with specified color for bright pixels
    r16 = (color[0] >> 3) << 11
    g16 = (color[1] >> 2) << 5
    b16 = color[2] >> 3
    fg_565 = r16 | g16 | b16

    pixels = []
    for y in range(img.height):
        for x in range(img.width):
            r, g, b = img.getpixel((x, y))
            lum = (r * 299 + g * 587 + b * 114) // 1000
            if lum > 80:
                pixels.append(fg_565)
            else:
                pixels.append(0x0000)

    with open(out_path, "w") as f:
        f.write("// Auto-generated by scripts/svg_to_rgb565.py — do not edit\n")
        f.write('#include "logo_rgb565.h"\n\n')
        f.write("const uint16_t g_logo_data[LOGO_W * LOGO_H] = {\n")
        for i, px in enumerate(pixels):
            if i % 8 == 0:
                f.write("    ")
            f.write(f"0x{px:04X},")
            if i % 8 == 7 or i == len(pixels) - 1:
                f.write("\n")
            else:
                f.write(" ")
        f.write("};\n")

    print(f"Generated {out_path}: {size}x{size} = {len(pixels)} pixels "
          f"({sum(1 for p in pixels if p)} visible, color=0x{fg_565:04X})")


if __name__ == "__main__":
    svg = sys.argv[1] if len(sys.argv) > 1 else "components/http_server/logo.svg"
    out = sys.argv[2] if len(sys.argv) > 2 else "components/display/src/logo_rgb565.c"
    size = int(sys.argv[3]) if len(sys.argv) > 3 else 56
    svg_to_rgb565(svg, out, size)
