// TaipanMiner v2 — floor entry point, `bbtool codegen`-composed.
//
// Composition root is now generated by `bbtool codegen` from `//
// bbtool:init` markers -- the vendored bb component headers (bb_log.h,
// bb_storage_nvs.h, bb_wifi.h, bb_system.h) plus this project's own
// consumer manifest (tm_wire.h, for TM-local calls with no natural
// component-header home) -- see scripts/tm_codegen.py (the pio pre:
// step that regenerates generated/bb_app_init.c before every build) and
// bbtool.toml's [capability.tm_floor]/[board.esp32-wroom32] tables. The
// MissingProvider guard this buys over the previous handwired root: a
// composed component whose init marker `requires=` a key nothing
// `provides=` (e.g. bb_wifi_autoinit requires=storage_nvs) is a hard
// codegen-time error, not a silent BB_ERR_NOT_FOUND at boot.
//
// True floor: boots, brings up logging, NVS, and WiFi (from stored creds,
// if any), prints a boot banner + reset reason, then idles. No
// mining/stratum/ASIC/display/LED/webui in this skeleton — those land as
// later PRs. bb_system's own public REQUIRES pulls in bb_http_server
// transitively (as it did under the prior handwired root too), but
// CONFIG_BB_HTTP_AUTOSTART=n (sdkconfig.defaults) keeps codegen's
// bb_http_autostart_init()/bb_system_routes_init() calls as graceful
// no-ops -- no port opened, no httpd task, matching this skeleton's
// still-headless intent.
#include "bb_core.h"
#include "bb_log.h"

// Hand-authored prototypes for `bbtool codegen`-generated
// generated/bb_app_init.c (gitignored -- build artifact, never committed).
// codegen emits no header of its own (wire.py's `render_source` only emits
// the .c + a link-set .cmake fragment; see .breadboard/examples/smoke/main/
// bb_app_init.h for the reference this mirrors), so this, their only
// caller, declares them itself. Signatures are fixed by
// commands/wire.py's `render_source`: three zero-arg entry points, all
// returning bb_err_t, first-error semantics per tier.
#ifdef __cplusplus
extern "C" {
#endif

bb_err_t bb_app_init_early(void);
bb_err_t bb_app_init_rest(void);
bb_err_t bb_app_init(void);

#ifdef __cplusplus
}
#endif

void app_main(void)
{
    bb_err_t err = bb_app_init_early();
    if (err != BB_OK) {
        // bb_app_init_early() already logs each failing entry's own
        // warning internally (first-error semantics, every entry still
        // runs) -- nothing more actionable to do here than continue.
    }

    // --- PRODUCER REGISTRATION SLOT (empty; comment marker only) ---

    // --- MINING/STRATUM SLOT (empty; comment marker only) ---

    err = bb_app_init_rest();
    if (err != BB_OK) {
        // Same first-error-per-tier semantics as above.
    }

    bb_log_i("taipanminer", "boot ok, idle");

    // app_main() returns; background work runs on component-owned tasks
    // (WiFi, mDNS, HTTP server, etc.). The scheduler keeps those tasks alive.
}
