#ifdef ESP_PLATFORM

#include "partition_fixup.h"
#include <string.h>
#include "esp_flash.h"
#include "esp_ota_ops.h"
#include "esp_log.h"
#include "esp_system.h"

static const char *TAG = "partition_fixup";

// Embedded expected partition table (generated by embed_partitions.py)
extern const uint8_t g_partitions_bin[];
extern const unsigned int g_partitions_bin_len;

#define PARTITION_TABLE_ADDR  0x8000
#define OTA_0_ADDR            0x20000
#define OTADATA_ADDR          0xF000
#define OTADATA_SIZE          0x2000
#define COPY_CHUNK_SIZE       4096

void partition_fixup_check(void)
{
    // Stub build (first compile before partitions.bin exists): skip
    if (g_partitions_bin_len <= 1) {
        return;
    }

    // Read current partition table from flash (static: main task stack is only 3584B)
    static uint8_t flash_table[4096];
    esp_err_t err = esp_flash_read(NULL, flash_table, PARTITION_TABLE_ADDR, g_partitions_bin_len);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "failed to read partition table: %s", esp_err_to_name(err));
        return;  // can't determine state, proceed with normal boot
    }

    // Fast path: table matches, nothing to do
    if (memcmp(flash_table, g_partitions_bin, g_partitions_bin_len) == 0) {
        return;
    }

    ESP_LOGW(TAG, "foreign partition table detected — starting fixup");

    // Find where we're currently running from
    const esp_partition_t *running = esp_ota_get_running_partition();
    if (running == NULL) {
        ESP_LOGE(TAG, "cannot determine running partition, aborting fixup");
        return;
    }

    ESP_LOGI(TAG, "running from 0x%08" PRIx32 " (size 0x%08" PRIx32 ")",
             (uint32_t)running->address, (uint32_t)running->size);

    // If we're not at our expected ota_0 offset, copy firmware there
    if (running->address != OTA_0_ADDR) {
        ESP_LOGI(TAG, "copying firmware from 0x%08" PRIx32 " to 0x%08" PRIx32,
                 (uint32_t)running->address, (uint32_t)OTA_0_ADDR);

        uint32_t copy_size = running->size;
        static uint8_t chunk[COPY_CHUNK_SIZE];

        // Erase-and-copy one sector at a time to avoid destroying source
        // when dest and source regions overlap (e.g. dest 0x20000-0x120000
        // overlaps source at 0x110000+).
        for (uint32_t offset = 0; offset < copy_size; offset += COPY_CHUNK_SIZE) {
            uint32_t len = COPY_CHUNK_SIZE;
            if (offset + len > copy_size) {
                len = copy_size - offset;
            }

            err = esp_flash_read(NULL, chunk, running->address + offset, len);
            if (err != ESP_OK) {
                ESP_LOGE(TAG, "read failed at offset 0x%" PRIx32 ": %s", offset, esp_err_to_name(err));
                return;
            }

            err = esp_flash_erase_region(NULL, OTA_0_ADDR + offset, COPY_CHUNK_SIZE);
            if (err != ESP_OK) {
                ESP_LOGE(TAG, "erase failed at offset 0x%" PRIx32 ": %s", offset, esp_err_to_name(err));
                return;
            }

            err = esp_flash_write(NULL, chunk, OTA_0_ADDR + offset, len);
            if (err != ESP_OK) {
                ESP_LOGE(TAG, "write failed at offset 0x%" PRIx32 ": %s", offset, esp_err_to_name(err));
                return;
            }
        }

        ESP_LOGI(TAG, "firmware copy complete (%" PRIu32 " bytes)", copy_size);
    }

    // Write our partition table at 0x8000 (one 4KB sector)
    // Requires CONFIG_SPI_FLASH_DANGEROUS_WRITE_ALLOWED=y in sdkconfig
    ESP_LOGI(TAG, "writing partition table at 0x%x", PARTITION_TABLE_ADDR);
    err = esp_flash_erase_region(NULL, PARTITION_TABLE_ADDR, COPY_CHUNK_SIZE);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "erase partition table failed: %s", esp_err_to_name(err));
        return;
    }

    err = esp_flash_write(NULL, g_partitions_bin, PARTITION_TABLE_ADDR, g_partitions_bin_len);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "write partition table failed: %s", esp_err_to_name(err));
        return;
    }

    // Erase otadata (8KB = two 4KB sectors at 0xF000)
    // All 0xFF means "boot from ota_0"
    ESP_LOGI(TAG, "erasing otadata at 0x%x (%" PRIu32 " bytes)", OTADATA_ADDR, (uint32_t)OTADATA_SIZE);
    err = esp_flash_erase_region(NULL, OTADATA_ADDR, OTADATA_SIZE);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "erase otadata failed: %s", esp_err_to_name(err));
        return;
    }

    ESP_LOGW(TAG, "partition fixup complete — rebooting");
    esp_restart();
}

#else
// Native build: no-op
#include "partition_fixup.h"
void partition_fixup_check(void) {}
#endif
