#ifdef ESP_PLATFORM

#include "partition_fixup.h"
#include <string.h>
#include "esp_flash.h"
#include "esp_ota_ops.h"
#include "esp_system.h"
#include "bb_log.h"

static const char *TAG = "partition_fixup";

// Embedded expected partition table (generated by embed_partitions.py)
extern const uint8_t g_partitions_bin[];
extern const unsigned int g_partitions_bin_len;

#define PARTITION_TABLE_ADDR  0x8000
#define OTA_0_ADDR            0x20000
#define OTA_1_ADDR            0x200000
#define OTA_SLOT_SIZE         0x1E0000
#define OTADATA_ADDR          0xF000
#define OTADATA_SIZE          0x2000
#define COPY_CHUNK_SIZE       4096

// Shared buffer for partition table and firmware copy operations
// Used sequentially: first for partition table read, then for copy loop
// Stack-allocated buffer would exceed main task stack (3584B), so static allocation is necessary
static uint8_t s_buf[4096];

// cppcheck-suppress unusedFunction ; called from src/main.c (cross-TU)
void partition_fixup_check(void)
{
    // Stub build (first compile before partitions.bin exists): skip
    if (g_partitions_bin_len <= 1) {
        return;
    }

    // Read current partition table from flash
    esp_err_t err = esp_flash_read(NULL, s_buf, PARTITION_TABLE_ADDR, g_partitions_bin_len);
    if (err != ESP_OK) {
        bb_log_e(TAG, "failed to read partition table: %s", esp_err_to_name(err));
        return;  // can't determine state, proceed with normal boot
    }

    // Fast path: table matches, nothing to do
    if (memcmp(s_buf, g_partitions_bin, g_partitions_bin_len) == 0) {
        return;
    }

    bb_log_w(TAG, "foreign partition table detected — starting fixup");

    // Find where we're currently running from
    const esp_partition_t *running = esp_ota_get_running_partition();
    if (running == NULL) {
        bb_log_e(TAG, "cannot determine running partition, aborting fixup");
        return;
    }

    bb_log_i(TAG, "running from 0x%08" PRIx32 " (size 0x%08" PRIx32 ")",
             (uint32_t)running->address, (uint32_t)running->size);

    // If we're not at our expected ota_0 offset, copy firmware there
    if (running->address != OTA_0_ADDR) {
        bb_log_i(TAG, "copying firmware from 0x%08" PRIx32 " to 0x%08" PRIx32,
                 (uint32_t)running->address, (uint32_t)OTA_0_ADDR);

        uint32_t copy_size = running->size;

        // Erase-and-copy one sector at a time to avoid destroying source
        // when dest and source regions overlap (e.g. dest 0x20000-0x120000
        // overlaps source at 0x110000+).
        for (uint32_t offset = 0; offset < copy_size; offset += COPY_CHUNK_SIZE) {
            uint32_t len = COPY_CHUNK_SIZE;
            if (offset + len > copy_size) {
                len = copy_size - offset;
            }

            err = esp_flash_read(NULL, s_buf, running->address + offset, len);
            if (err != ESP_OK) {
                bb_log_e(TAG, "read failed at offset 0x%" PRIx32 ": %s", offset, esp_err_to_name(err));
                return;
            }

            err = esp_flash_erase_region(NULL, OTA_0_ADDR + offset, COPY_CHUNK_SIZE);
            if (err != ESP_OK) {
                bb_log_e(TAG, "erase failed at offset 0x%" PRIx32 ": %s", offset, esp_err_to_name(err));
                return;
            }

            err = esp_flash_write(NULL, s_buf, OTA_0_ADDR + offset, len);
            if (err != ESP_OK) {
                bb_log_e(TAG, "write failed at offset 0x%" PRIx32 ": %s", offset, esp_err_to_name(err));
                return;
            }
        }

        bb_log_i(TAG, "firmware copy complete (%" PRIu32 " bytes)", copy_size);
    }

    // Write our partition table at 0x8000 (one 4KB sector)
    // Requires CONFIG_SPI_FLASH_DANGEROUS_WRITE_ALLOWED=y in sdkconfig
    bb_log_i(TAG, "writing partition table at 0x%x", PARTITION_TABLE_ADDR);
    err = esp_flash_erase_region(NULL, PARTITION_TABLE_ADDR, COPY_CHUNK_SIZE);
    if (err != ESP_OK) {
        bb_log_e(TAG, "erase partition table failed: %s", esp_err_to_name(err));
        return;
    }

    err = esp_flash_write(NULL, g_partitions_bin, PARTITION_TABLE_ADDR, g_partitions_bin_len);
    if (err != ESP_OK) {
        bb_log_e(TAG, "write partition table failed: %s", esp_err_to_name(err));
        return;
    }

    // Duplicate ota_0 into ota_1 for rollback safety
    // Prevents anti-rollback from booting into garbage if mark-valid doesn't fire
    bb_log_i(TAG, "duplicating ota_0 -> ota_1 for rollback safety");
    for (uint32_t offset = 0; offset < OTA_SLOT_SIZE; offset += COPY_CHUNK_SIZE) {
        uint32_t len = COPY_CHUNK_SIZE;
        if (offset + len > OTA_SLOT_SIZE) {
            len = OTA_SLOT_SIZE - offset;
        }

        err = esp_flash_read(NULL, s_buf, OTA_0_ADDR + offset, len);
        if (err != ESP_OK) {
            bb_log_e(TAG, "ota_1 copy: read failed at offset 0x%" PRIx32 ": %s", offset, esp_err_to_name(err));
            return;
        }

        err = esp_flash_erase_region(NULL, OTA_1_ADDR + offset, COPY_CHUNK_SIZE);
        if (err != ESP_OK) {
            bb_log_e(TAG, "ota_1 copy: erase failed at offset 0x%" PRIx32 ": %s", offset, esp_err_to_name(err));
            return;
        }

        err = esp_flash_write(NULL, s_buf, OTA_1_ADDR + offset, len);
        if (err != ESP_OK) {
            bb_log_e(TAG, "ota_1 copy: write failed at offset 0x%" PRIx32 ": %s", offset, esp_err_to_name(err));
            return;
        }
    }
    bb_log_i(TAG, "ota_1 duplication complete (%" PRIu32 " bytes)", OTA_SLOT_SIZE);

    // Erase otadata (8KB = two 4KB sectors at 0xF000)
    // All 0xFF means "boot from ota_0"
    bb_log_i(TAG, "erasing otadata at 0x%x (%" PRIu32 " bytes)", OTADATA_ADDR, (uint32_t)OTADATA_SIZE);
    err = esp_flash_erase_region(NULL, OTADATA_ADDR, OTADATA_SIZE);
    if (err != ESP_OK) {
        bb_log_e(TAG, "erase otadata failed: %s", esp_err_to_name(err));
        return;
    }

    bb_log_w(TAG, "partition fixup complete — rebooting");
    esp_restart();
}

#else
// Native build: no-op
#include "partition_fixup.h"
void partition_fixup_check(void) {}
#endif
